# Install MySQL Server and Other Important Dependencies
# sudo apt install mysql-server python3-mysqldb -y
- name: Install MySQL server
  apt:
    name:
      - mysql-server
      - python3-mysqldb
    state: present
  tags: mysql

# sudo systemctl start mysql
- name: Start the MySQL service
  service:
    name: mysql
    state: started
  tags: mysql