- name: Set mysql root user password
  mysql_user:
    login_user: '{{ mysql_login_user }}'
    login_password: '{{ mysql_root_password }}'
    name: '{{ mysql_login_user }}'
    password: '{{ mysql_root_password }}'
    state: present
    host: '{{ item }}'
    check_implicit_admin: yes
  loop:
    - 127.0.0.1
    - ::1
    - localhost
  tags: mysql

# Also we want to remove anonymous users and default databases. 
# sudo mysql -u root -e 'UPDATE mysql.user SET plugin="mysql_native_password" WHERE user="root" AND host="localhost"'

- name: Delete all anonymous mysql users
  mysql_user:
    login_user: '{{ mysql_login_user }}'
    login_password: '{{ mysql_root_password }}'
    name: ''
    host_all: yes
    state: absent
  tags: mysql

- name: Remove test database
  mysql_db:
    login_user: '{{ mysql_login_user }}'
    login_password: '{{ mysql_root_password }}'
    name: test
    state: absent
  tags: mysql