# Next, we want to configure our database, so we set a default password for the root user; this allows us to now 
# create our new password so we can log in to the database.
# Next we create a database, and then a user, we grant the user all the necessary permissions on the database
# Ensure the user can use the database, and then log in as root user to set a password for the created user

- name: Create a new mysql user
  mysql_user:
    login_user: '{{ mysql_login_user }}'
    login_password: '{{ mysql_root_password }}'
    name: '{{ DB_USER }}'
    password: '{{ USER_PASSWORD }}'
    priv: '*.*:ALL,GRANT'
    state: present
  register: new_user
  changed_when: new_user.msg != "Privileges updated"
  tags: mysql

- name: Create new database
  mysql_db:
    login_user: '{{ mysql_login_user }}'
    login_password: '{{ mysql_root_password }}'
    name: '{{ DB_NAME }}'
    state: present
  tags: mysql